### ISSUE TITLE
Add Web Speech API

### ISSUE THREAD

**Issue by snyderp** [snyderp/web-api-manager#17]
https://w3c.github.io/speech-api/webspeechapi.html

**Comment by timothymathison** [comment]
I'm interested in implementing this feature.
FYI, myself and some research partners will be working on it. We might have questions; if so we will let you know.

**Comment by snyderp** [comment]
Hi @timothymathison 

That'd be great, go for it!  If I can help in anyway, please let me know. 

Also, if you think it might take a moment to complete on your end, I just wanted to give you a heads up that I think some other folks at UIC might be tackling this issue too (I don't know where it stands at the moment…).  All that is to say, if you're specifically interested in the "Web Speech API", then go for it, that'd be terrific.  But if you're generally interested in expanding the scope of what the extension can block, you might also consider selecting other recent Web API standard.

Eitherway, just let me know if there is anything I can do to help!

**Comment by snyderp** [comment]
fixed by #37
