### ISSUE TITLE
Unmodified DOM is still visible to frames via `HTMLIFrameElement.contentWindow`

### ISSUE THREAD

**Issue by snyderp** [snyderp/web-api-manager#20]

**Comment by snyderp** [comment]
https://browserleaks.com/javascript

**Comment by snyderp** [comment]
Issue comes up when the child iFrame doesn't have a `src` to load, and so the webRequest API never fires…

**Comment by publicarray** [comment]
Thanks for fixing it so fast. I assume this is not the fix we both wanted, but I guess it will do. 👍

**Comment by snyderp** [comment]
Your message was very helpful too.  Turns out the Brave folks have the same issue, so I was able to send them the same fix https://github.com/brave/browser-laptop/issues/11683
