### ISSUE TITLE
Cannot sign in to github.com even when all "blocked standards" are cleared

### ISSUE THREAD

**Issue by crssi** [snyderp/web-api-manager#3]
Cannot sign in to github.com even when all "blocked standards" are cleared.
It works only if I disable WAM extension.

Cheers

**Comment by snyderp** [comment]
I do not have any guesses whats going on here, but I'm sure it must be the same issue as issue #2 (i'll make that issue more general).  My only guess at this moment that its the XSS Auditor, but thats a blind guess

Eitherway, this is something I'll have to get fixed right away.  Thanks for the nudge

**Comment by crssi** [comment]
Nice job. Thank you

**Comment by crssi** [comment]
on 0.9.2 facebook.com (not that I am using it) is broken even when all "blocked standards" are cleared
Guess this will be resolved with #11

**Comment by snyderp** [comment]
@crssi Yep, this should be fixed now.  Thanks for following up.  I added a test for Facebook, and its working now for me too with manual use too.  If you're still seeing any trouble though, please let me know so I can get it straight.  Thanks again for the help / extra eyes!
