### ISSUE TITLE
Sharing settings 

### ISSUE THREAD

**Issue by theWalkingDuck** [snyderp/web-api-manager#38]
For two or more domains which share the same setup (a non default setup),
I think it would be better to set the rule as follows:

`*.abc.net,*.xyz.org,*.foo.com,*.bar.com`

That means the "pattern" field needs to be an array of domains.

```
[
	{
		"pattern":[
			"*.abc.net",
			"*.xyz.org",
			"*.foo.com",
			"*.bar.info"
		],
		
		"standards":[
			"Ambient Light Sensor API",
			"Battery Status API",
			"Beacon",
			......
		]
	}
]
]
```
Thank you so much for this exceptional extension !

**Comment by snyderp** [comment]
@theDuckIsAlive I think this is a great idea.  I think i'll need to rework the structure for storing block rules will need to be reworked pretty heavily once I get the subscriptions work in.  (which, i hope will be the next release after 0.9.11, and I'll call it 1.0).  Will need to think it through to make sure I don't goof it up too bad

It'll need to think it through, but this is a great suggestion.  Any other suggestions you have for better / easier to understand ways of assigning rules would be great!

**Comment by snyderp** [comment]
I'm going to close this bug for now, since getting subscribing to rules working will require a similar but different re-working of  how preferences are encoded.  But I will keep these suggestions in mind when coding that up.  Thanks!
