### ISSUE TITLE
Loging improvement suggestion

### ISSUE THREAD

**Issue by crssi** [snyderp/web-api-manager#4]
Can you add additional info by which "Blocked standard" something was blocked.
Otherwise, it is quite hard to find out what needs to be un-checked in the settings to restore functionality.

Thank you
Cheers

**Comment by snyderp** [comment]
Thanks, this is a great idea!  I will get this added into the next update for sure

**Comment by crssi** [comment]
Cool, thank you 👍 

Maybe it would be even better to have the info of blockage in the window/popup that appears when you click on Icon (what is this kind of window called?)

**Comment by snyderp** [comment]
Ok, this is finally in place with `3a4df42`.  I need to poke at it some more, but should be part of the next release.
