### ISSUE TITLE
Add feature level granularity for advanced users

### ISSUE THREAD

**Issue by snyderp** [snyderp/web-api-manager#42]
Would be nice if users just want to block subsets of a standard, even if the UI was rough

**Comment by snyderp** [comment]
FWIW, i am working on this now in branch `42-custom-feature-blocking`

**Comment by snyderp** [comment]
Fixed in 16d2232dc08d8f479de0a0c7894e770e15cdff01

**Comment by n8v8R** [comment]
WIN10 _x64 1709 16299.125 with FF58/59 _x64

WAM 0.9.24 (- add ability to block specific features, without blocking the entire standard (fixes #74)

I am not seeing any such option. Where is it supposed to show?

**Comment by snyderp** [comment]
Well, thats embarrassing…

I didn't merge in all the changes i meant too.  Thank you for catching it!  I just uploaded 0.9.25, and it should be available any minute.  When you get the update, you should see the field to add these features in the below field.

Sorry for the headache!


<img width="981" alt="screen shot 2018-02-13 at 3 19 45 am" src="https://user-images.githubusercontent.com/76526/36142126-c12b44fe-106c-11e8-9ebd-387f73f69595.png">

**Comment by n8v8R** [comment]
No to apologize, your fan community is just glad and grateful for services provided. Catching and reporting a bug is the least one can do to support development

Now, once #53 is sorted all will be well ;)
