### ISSUE TITLE
Issue with copying to clipboard on keeweb

### ISSUE THREAD

**Issue by rEnr3n** [snyderp/web-api-manager#44]
WebAPI manager v0.9.13
Config: all clear

I use keeweb (self-hosted) as my password manager for some time and I'm having issue with your latest version.

My keeweb is opened in a browser's tab. I copy my credentials from there.

Copy by clicking on the username item = FAIL
Copy by clicking on the password item = FAIL
Copy username using keyboard shortcut (Ctrl+B) = FAIL
Copy password using keyboars shortcut (Ctrl+C) = SUCCESS

The examples at https://clipboardjs.com/ work however. I have to disable this extension to copy my credentials.

**Comment by snyderp** [comment]
Hello @rEnr3n, that is very surprising, I cannot think of why that would be happening.  If you are blocking no standards for a domain, the extension fast paths out and doesn't make any changes to do the page.  

I tried to recreate the issue through the following steps:

1.  open https://app.keeweb.info/
2.  click "New"
3.  click the "+" icon to create a new entry
4.  create a new sample entry using the following values
    -    title: test
    -    username: petename
    -    password: petepass
5.  click on the username (i see the "copied" note appear) and verify that its in the clipboard
6.  same as above, but password

I'm running the latest version of the extension, on Firefox 57, and blocking the below standards:

```
[
  {
    "pattern": "(default)",
    "standards": [
      "Ambient Light Sensor API",
      "Battery Status API",
      "Beacon",
      "Gamepad",
      "Geolocation API",
      "Geometry Interfaces Module Level 1",
      "Media Source Extensions",
      "Scalable Vector Graphics (SVG) 1.1 (Second Edition)",
      "Vibration API",
      "Web Audio API",
      "Web Notifications",
      "WebGL 2.0",
      "WebGL Specification",
      "WebRTC 1.0: Real-time Communication Between Browser",
      "WebVTT: The Web Video Text Tracks Format"
    ]
  }
]
```

**Comment by snyderp** [comment]
If you can provide more information about the issue though, or how I can recreate it, I would be very happy to sort out whats going on. 

Thank you for the report!

**Comment by rEnr3n** [comment]
I am on chrome. I think it's solved now. I just deleted ALL my browsing data. The extension is also updated to 0.9.14 and keeweb to 1.6.1.

Before that, I recently deleted my browsing data except the cookies. That didn't work.
