### ISSUE TITLE
"The Web Console logging API (console.log, console.info, console.warn, console.error) has been disabled by a script on this page."

### ISSUE THREAD

**Issue by jawz101** [snyderp/web-api-manager#45]
I saw this msg on https://forum.xda-developers.com

I think it's from a 1st party script from the search company they use, algolia.net but can't tell much else.

https://forum-lw-1.xda-cdn.com/clientscript/algolia/js/search.js?v=1511529156

**Comment by jawz101** [comment]
er it may actually be https://forum-lw-1.xda-cdn.com/clientscript/2015.head.min.js?v=1511529156

`if(!window.console||!console.firebug){window.console={};var names=["log","debug","info","warn","error","assert","dir","dirxml","group","groupEnd","time","timeEnd","count","trace","profile","profileEnd"]`

I don't know if that's worth anything of interest but it looks like maybe they disable debugging on Firefox I guess?

Either way, I guess you can close this if it doesn't mean anything.

**Comment by Atavic** [comment]
That code hides errors on the console.

**Comment by snyderp** [comment]
Actually, I can work around this, it shouldn't be possible for the page to stop the extension from operating in this way.  I'll get a fix in for the next release.  The real issue is building tests for it, since (as far as I can tell) gekcodriver can't read the jslog yet…

**Comment by snyderp** [comment]
fixed with 273575a

**Comment by jawz101** [comment]
Got the update, it didn't change anything


![scr](https://user-images.githubusercontent.com/14151703/33531304-0e38e93a-d883-11e7-8f66-68e553e9a85c.jpg)

**Comment by jawz101** [comment]
seems like clearing my browser data + the fix now it looks good.

**Comment by snyderp** [comment]
I see that message, but if you try to trigger blocked functionality (ex. block canvas on the site, and then run `CanvasRenderingContext2D.prototype.clearRect()` in the console), you should still see the error loged

**Comment by snyderp** [comment]
oh, ok, beat me to it, glad to hear :)

**Comment by jawz101** [comment]
yep.  I'm looking around for things to help with making it easier to find API's to block.  Like maybe some places where others have already pulled [together such lists.](https://github.com/webrtc-uwp/chromium-tools/blob/master/blink_rename_merge_helper/data/idl_blocklist.txt)  still looking, though.

**Comment by snyderp** [comment]
Thank you!  Just let me know if I can be helpful.  Another good way of doing so might be to check the release notes for the last couple of Firefox and Chrome releases.  You may be startled how many new standards are added each month!
