### ISSUE TITLE
request an option to notify user with requests per API

### ISSUE THREAD

**Issue by jawz101** [snyderp/web-api-manager#46]
It would be nice if, at some point, you could have check boxes beside each API to also pop-up a little notification with an alert that "Battery API  was allowed/blocked for example.com."

Something that came up faded away after 2 or 3 seconds.  It would kinda give the use an idea of what's popular on sites and I think it could  help visualize how they're used without jumping to the console.

**Comment by jawz101** [comment]
I want to say that would be optional for each API.  I wouldn't want to know every time Html gets called but I may for some of the obscure ones every now and then.

**Comment by n8v8R** [comment]
Suppose such info could be gathered from the console log, but it certainly such notification as described for API actually deployed on a website would be convenient.

**Comment by n8v8R** [comment]
Seen a really comfortable/convenient way to display logs with whitelisting option at this extention https://github.com/schomery/policy-control, and would like it here too

**Comment by snyderp** [comment]
I think this is a great idea, and in the same vein as #4.

My thinking for an option here is a button in the popup / browser action, that says something like "what was blocked on this page".  That'd open up a new tab, that looked something like this:

```
Blocked standards for <url of tab>
===
- standard name 1
    * method name 1
    * method name 2
- standard name 2
    * method name 1

Blocked standards for sub-document: <url for frame or iframe>
---
- standard name 1
    * method name 1
    * etc
```

Thoughts?

**Comment by jawz101** [comment]
I very much like that for the current pop-up but, in the vein of this request, I was thinking of a mechanism that would show a little popup when, say, the battery API was used.

There's an add-on on AMO called [Self-Destroying Cookies](https://addons.mozilla.org/en-US/firefox/addon/self-destructing-cookies-1/) that pops up a quick alert whenever a tab is closed and coookies were removed.  It pops up for a few seconds then disappears.

![image](https://user-images.githubusercontent.com/14151703/33620788-7ed99a1e-d9ae-11e7-9435-5ee8a6c5cf02.png)

**Comment by n8v8R** [comment]
@jawz101 A popup might be ok for a single API block, but I am not sure it would be convenient if there are 5, 10, 15 API being blocked (might be unlikely but not impossible for users with agressive settings - my end put a block on 30+ APIs as default).

@snyderp Looks pretty much in line with #4 indeed (perhaps one can be closed thus reducing the number of open tickets :)

Posted the example of Policy Control as its logs handling appeals rather comfortable. The number of blocks shows as badge counter on the icon and then it is 2 mouse clicks to the logs, one on the `icon` and then on `logs` in the popup from the icon. Perhaps adding a button here
 
![log button](https://user-images.githubusercontent.com/13611490/33623063-0b7ce7fa-d9f0-11e7-8f45-587441c7a8a5.png)

Which then opens a new tab with the logs, displaying what actually been blocked. And to make it user friendly/convenient add button(s) to whitelist an API for a domain or ruleset/pattern (#38)

**Comment by jawz101** [comment]
@n8v8R take a look at the first sentence in my first post:

> It would be nice if, at some point, you could have check boxes beside **each** API to also pop-up a little notification with an alert that "Battery API was allowed/blocked for example.com."

I said that it would be a checkbox beside each API to allow any particular API to trigger a popup.  That way you could quickly know if some of the more rarely used API's are being used.

You kinda hijacked my original request with a completely different request for a logging mechanism.  Make your own issue for that.

**Comment by snyderp** [comment]
@n8v8R @jawz101 

Lets move the improved logging conversation to #4 (I have this mostly done at this point, if you're curious or wanna help debug it its in the `4-improve-logging-interface` branch).

Regarding @jawz101 initial request (which I didn't mean to hijack, apologies :) ), I think this could be a neat addition for folks who are interested, but its going to be a long time before I can get to it.  I'd welcome a PR for it, but at least for me, I won't be able to consider until after I get the subscription code finalized, in a few releases

**Comment by snyderp** [comment]
I'm going to close this issue for now, since I think the enhanced logging does "good enough" for now, and this enhancement (while useful) isn't on my radar anytime soon.  I'd consider a PR if you're interested in it (lets discuss first, please :) ) but I'm going to close for the time being.  Thank you again for your input though, I appreciate the thoughtfulness :)
