### ISSUE TITLE
I don't think the console API is blocking this test of count

### ISSUE THREAD

**Issue by jawz101** [snyderp/web-api-manager#47]
https://www2.w3c-test.org/console/console-count-logging-manual.html

test suite info:
http://web-platform-tests.org
https://github.com/w3c/web-platform-tests
https://developer.mozilla.org/en-US/docs/Mozilla/QA/web-platform-tests
https://chromium.googlesource.com/chromium/src.git/+/master/docs/testing/web_platform_tests.md
https://github.com/MicrosoftEdge/web-platform-tests

**Comment by snyderp** [comment]
Hmm, interesting, i'm not sure whats going on here, but I'll dig into it today.  Thanks for the issue!

**Comment by snyderp** [comment]
Fixed, turns out that `Console.prototype.*` isn't a thing anymore (or maybe it never was and I goofed from the start).  Either way, I updated these to point to the `console` singleton, and should be all good.  I'll push out a fix right away.  Thanks again!
