### ISSUE TITLE
Differences in Chrome vs Firefox handling of tabs.query

### ISSUE THREAD

**Issue by snyderp** [snyderp/web-api-manager#52]
Firefox returns a Promise, Chrome wants a callback, need to figure out a way to account for both.

**Comment by snyderp** [comment]
fixed with `098a2a0`

**Comment by ghostwords** [comment]
Firefox should works with callbacks too.

>As a porting aid, the Firefox implementation of WebExtensions supports chrome, using callbacks, as well as browser, using promises. This means that many Chrome extensions will just work in Firefox without any changes. However, this is not part of the WebExtensions standard, and might not be supported by all compliant browsers.

- https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Chrome_incompatibilities

**Comment by snyderp** [comment]
Ah, interesting!  I didn't know!  I'm going to keep to the Promise API (w/ an exception for Chrome) in case other browsers get to the point where WexExtensions work equally as well, but good to know about this.  Thanks for the pointer :)
