### ISSUE TITLE
toggle section links/buttons (feature)

### ISSUE THREAD

**Issue by atomGit** [snyderp/web-api-manager#57]
might be good to add a method to disable all rules per section, such as by adding a button to each section header that would toggle the state of all rules between disabled, enabled and restore to previous

this would help with adding rules in bulk as well as troubleshooting a particular website

**Comment by snyderp** [comment]
I dig it.  I should be able to get something like this is for the next release.  I dont know what UI for "restore to previous" could look like, but the "block all" / "unblock all" toggle makes sense to me.

Can you explain the UX flow you're thinking for the "restore" option?

**Comment by atomGit** [comment]
i'm not sure how that might best be implemented, but off the top of my head...

you have enable all, disable all (both buttons can be combined) and restore - from a coding POV, the flow is the same; you effect changes as items are selected/deselected, but when the options page is first opened, you backup the state of each option for each section and then if they click restore in any particular section, you restore the controls for that section to the backed up state - you could dump the backup once the options page is closed, or keep it until it is reopened again

so that results in adding 2 buttons and a bit of code to backup and restore the control states, but you could do it with 1 button that cycles between enable all, disable all and restore - slightly less cluttered UI i guess

because of the number of options in some of the sections, i think it's a pretty good idea to have that restore option - that way users can enable/disable stuff as they please for troubleshooting and, if that wasn't the problem, they can restore the previous state - of course the other way would be to allow the user (or you could do it for them) to create a 2nd global testing template that they could use for testing and then add an option to assign a domain to it, or use it as default

**Comment by snyderp** [comment]
Ah, I better understand the proposal now.  I think for now I'll move forward on the convenience "block all / allow all" button per standard grouping.

I understand the use case you're describing, and it makes sense, but I think having additional per-rule -> per-standard-grouping state that the needs to maintain is going to be more than I can manage at the moment given other priorities.  

I'll work on getting the convenience toggles for the next release though.  Thanks again :)
