### ISSUE TITLE
display which API requests were made (feature)

### ISSUE THREAD

**Issue by atomGit** [snyderp/web-api-manager#58]
dunno if this is possible, but i think it would be of great benefit for troubleshooting, etc., to be able to know which APIs a site is attempting to access - for example, using a little CSS or whatever to visually highlight all of the API items that a given site is wanting to use when the Domain Rules UI is opened

i think this would make this add-on accessible to a much wider audience of non-geeks - even for myself, the API descriptions are often useless because they don't provide simple examples of how an API is used, so in order to use this add-on, a lot of reading and research is necessary

**Comment by snyderp** [comment]
I agree, this would be great.   I think this is the same as #22, though your explanation of it is much clearer :)

I'm thinking of calling it "passive" mode or something like that, where it'll log all the features that were used, but not block anything.  Would that cover the functionality you're imagining?

**Comment by atomGit** [comment]
not sure that loading an untrusted site in 'passive' mode for testing would be a good idea ???

what i'm thinking is that one could set all options in the default template to 'block all', then you load a site and find that something you need to work is busted, so you open the options UI and you get instant visual feedback as to exactly what APIs that particular site is wanting to access in the form of some css styling or whatever, such as changing the background color for each API option the site wants - so now you can pick the likely candidate(s) and un-block that API

your idea of a log sounds like it would be much simpler from a coding POV, though i think i'd like to see the log right on the options page or have a link to the console or whatever ... and then later on, after you implement the log and i still continue to pester you for a visual indicator, maybe the log code will come in handy for setting the CSS .. LOL

**Comment by snyderp** [comment]
I'm better understanding what you're thinking now, thanks for clarifying. 

Have you tried the new logging interface?  I think it does 90% of what you're describing (it shows which standards and features are blocked in a tab, just not on the same page as the "which standards to block" interface.

I see the appeal of the combined interface for the logging and configuration systems, but I think it would be difficult to combine them (what, for example, to do when there are multiple tabs open that match a single blocking rule, etc).

If you haven't already, could you check out the new logging interface I added in the most recent release, and let me know if its helpful for ya? :)

**Comment by atomGit** [comment]
in my personal opinion the logging UI is ok but not ideal because you can't enable/disable options from it, plus there's the caveat of an apparent performance hit with logging enabled and you have to go to the options UI to disable/enable it each time you have an issue

so for troubleshooting, one would have to view the log, remember the option names, and then switch to the rules UI to make changes

> I think it would be difficult to combine them (what, for example, to do when there are multiple tabs open that match a single blocking rule, etc).

you highlight the APIs for the domain loaded in the active tab and ignore the others? i'm also wondering if it wouldn't be good to add a button to the tool-bar button context menu that would create a fresh template for the current domain instead of having to manually add the domain name, then click 'add' - so for github for example, you have the 'allow all' button and next to that you could add a 'add' button

so you have the default template loaded and something is broken - you want to create a new template for that domain, so you just click an 'add example.com' button and the fresh template will display what APIs that domain want to access

**Comment by snyderp** [comment]
I'm going to close this, since I think the new logging interface is (hopefully) "good enough" to debug what a site wants to use, and I think issue #64 should cover the last item mentioned.

If you think i'm off base though, please let me know :)

**Comment by atomGit** [comment]
fine with me :)

**Comment by Atavic** [comment]
A nice report about API usage: https://webcookies.org/reputation/rules/

GH Page: https://github.com/kravietz/cookie-security

Presentation: https://ipsec.pl/cookies-privacy/2013/presenting-webcookiesorg.html
