### ISSUE TITLE
Querying block rules...

### ISSUE THREAD

**Issue by rEnr3n** [snyderp/web-api-manager#63]
WebAPI Manager v0.9.19
Chromium v63.0.3239.108

When I click the extension icon it just says "querying block rules..." I tried clearing the cache. I also tried deleting these folders:
```
~/.cache/chromium
~/.config/chromium
```
I still have this issue. I don't have this issue on firefox however.

**Comment by snyderp** [comment]
@rEnr3n Ah, thank you for catching this!  The result of more unexpected ways that the Chrome API differs from the standard.  Fixing now, and will have a release out in the next few hours.  Thanks!
