### ISSUE TITLE
Enhancement : remember personnal configurations

### ISSUE THREAD

**Issue by mazesy** [snyderp/web-api-manager#64]
Default configs -- Lite, Conservative, Aggressive -- are fine when using Web Api Manager in the scope of "fine tuning". Maybe am I not the only one to not understand all settings proposed by this great add-on, and in my case the aim is to find the best ratio between max efficiency and min per-site intervention. I use already uBlock Origin in its "hard mode" (block all than allow specifics) because I understand uBO's settings, but unfortunately cannot adopt this policy when it comes to Web Api Manager because I lack understanding of all settings.

My experience.
1- Conservative Mode seems OK for a wide majority of sites I've run it  up to now.
2- Youtube.com requires no specific pattern (with 'Conservative') when cookies are forbidden for youtube.com : the site seems to require specific APIs only in order to build its cookies... that was a true surprise for me.
3- Virustotal.com won't make it unless set as permitted, seems to refuse the slightest blocking.

From there on I could keep the 'Conservative' mode as the pattern for (default) and my post would then be obsolete. The point is I wish to add to what is set by 'Conservative' more settings which fine-tune my browser yet remain 'universal' enough to be associated to the (default) pattern ... but one or two settings will require a site-specific pattern (I have in mind HTML: Web Storage).

I'd like to be able to fix my (default) pattern as a Configuration setting aside of the default ones in order to call it as a base for sites which require say one change. As of now I have to recall 'Conservative' the re-apply my my settings (those I've set for (default) and do the site-specific switch (say, HTML: Web Storage).

Thanks.

**Comment by snyderp** [comment]
This seems like a great idea!  I'll dig into it now and hope to get it into the next release.  thanks for the suggestion!
