### ISSUE TITLE
problem with privacy.firstparty.isolate in Firefox

### ISSUE THREAD

**Issue by earthlng** [snyderp/web-api-manager#65]
"Unable to find Web API Manager settings: ..." when `privacy.firstparty.isolate` is set to true.

tested with v0.9.20 in Firefox Nightly 59.0a1 (2018-01-05)

**Comment by n8v8R** [comment]
known issue https://github.com/snyderp/web-api-manager/issues/53

**Comment by snyderp** [comment]
@n8v8R thanks for catching that :)
