### ISSUE TITLE
[Request] Is it possible to make the extension work with Vivaldi Browser?

### ISSUE THREAD

**Issue by Tykina** [snyderp/web-api-manager#68]
I am unsure if you are aware of Vivaldi, it is a fork of Chromium. (Vivaldi Release is based on Chromium 62, Vivaldi Dev Build is Chromium 64).

When loading web-api-manager in Vivaldi, the popup menu shows :

Blocking Rules

Querying block rules...

This never completes.

If I go to vivaldi://extensions, and click on 'Inspect Views: background page', I see the following error in the console :

Error in response to webNavigation.getAllFrames: TypeError: Cannot read property 'map' of null
    at Object.browserLib.getAllFrames.frameResults [as callback] (chrome-extension://hojoljbhkebfjalcbnfmoiljfidcmcmj/background_scripts/messages.js:63:26)
    at Object.getAllFrames (chrome-extension://hojoljbhkebfjalcbnfmoiljfidcmcmj/lib/browser.js:98:38)
    at Object.browserLib.queryTabs.tabs [as callback] (chrome-extension://hojoljbhkebfjalcbnfmoiljfidcmcmj/background_scripts/messages.js:61:28)

**Comment by snyderp** [comment]
Thanks for raising the issue.  I'll take a look.  If its something I can fix with a minor change, I'll go for it.  Thanks again for the nod!

**Comment by snyderp** [comment]
I'm digging into this now.  The issue seems to be that `browser.webNavigation.getAllFrames` does not behave according to the spec in the browser. 

@Tykina Do  you have experience working with the dev team on the browser?

**Comment by snyderp** [comment]
FWIW (to all on the issue) I've opened a bug with the Vivaldi folks about the behavior of `browser.webNavigation.getAllFrames`

**Comment by Tykina** [comment]
> @Tykina Do you have experience working with the dev team on the browser?

I'm afraid not. Thanks for looking into this, and reporting the issue to them.

**Comment by Tykina** [comment]
@snyderp - I am not sure if you fixed it, or they fixed it, but I can confirm that WebAPI Manager is now working correctly in Vivaldi's 'Snapshot' version (1.15.1104.3)

**Comment by snyderp** [comment]
Ah that’s great!  I’m guessing the re-synced with chromium’s web extension implementation. I’ll close this now then. Thanks very much for the heads up! :)
