### ISSUE TITLE
Remove outdated `moz` prefixes from standards

### ISSUE THREAD

**Issue by snyderp** [snyderp/web-api-manager#7]
Some of the feature keypaths still have the old `moz` prefixes.  They're not needed anymore

**Comment by snyderp** [comment]
Unfortunately, i think these are unrelated issues. the `-moz` prefixes are CSS selectors.  `moz` prefixes I'm describing in this issue have to do with the extension knowing which JS / Web API methods to block.  So, I don't think this extension will help google-on-firefox-mobile results.  :(

**Comment by bengansukh** [comment]
For example "mozRTC*" would need both unfixed and prefixed versions.
