### ISSUE TITLE
Doesn't work in Firefox 52 ESR

### ISSUE THREAD

**Issue by enomat** [snyderp/web-api-manager#70]
Installed it in Firefox 52 ESR, but it doesn't work.

When I click on the icon in the toolbar I get this and nothing happens:

```
Blocking Rules

Querying block rules…
```

If I click on "Configure blocking rules", it will open a blank page (the title of the blank tab is "Web API Manager Configuration").

**Comment by snyderp** [comment]
Hmm, odd, i will look into this now, thanks for the report!
