### ISSUE TITLE
[ISSUE] Even ONE ANY rule partially breaks web-functionality

### ISSUE THREAD

**Issue by iWARR** [snyderp/web-api-manager#72]
Opera Developer, Win8.1 [x64]

**How to reproduce:**

1) Go to inside any topic on blogs.opera.com, for example:
https://blogs.opera.com/desktop/2018/02/opera-52-0-2857-0-developer-update/

Normally, at the bottom of page you should see DISQUS loading.
I can obtain it on only one way: absolutely all rules should be cleared.

If I'll set even **one any** blocking rule (even such "safe" as `Geolocation API`), then DISQUS will not load.
So, here is nothing about blocking configuration. Setting any rule breaks functionality from the start.

2) Same situation with YouTube.
(I have read your "Useful Page Configurations", this doesn't matter for this issue).

• Even one any rule breaks autoplay inside the Playlist, also I have to click 2 times to open main Playlist to see videos inside. 

• In Full screen mode pressing forward to next video button does quit from this mode immidiately, that is much unexpected.

It's not about DISQUS or YouTube (they are only test examples), I suggest some issues with WebAPI Manager extention or Opera compatibility.

Thanks.

**Comment by snyderp** [comment]
This is unfortunately a limitation of the approach.  Because of the way browsers have implemented WebExtensions, the extension needs to block parent frames from reaching into the content of iframes.  The short explanation is that this is needed to keep parent frames from getting blocked functionality out of child frames, before the extension can block the functionality in the child frames.

As this is a known and necessary limitation of the extension im going to close this bug, but I'm going to work on issue #73 which will allow a default "less secure, but more compatible" mode

**Comment by iWARR** [comment]
Your new "safe mode" `Block cross-frame access` works well on Opera Dev - no stuck, no issues with YouTube or DISQUS. I can continue manage blocking configurations and have main web-functionality working as expected on Opera Dev.

Furthermore, I'm already had some APIs turned off in the experimental settings, before having your extension installed first time.

-------------------------------

Just inform you, what options I have in the Opera Dev.
Guess, the next ones are the most significant options, relative to the cross-frame access (Opera Dev):

• **Reduce default 'referer' header granularity** - `#reduced-referrer-granularity` - [Enabled]

`If a page hasn't set an explicit referrer policy, setting this flag will reduce the amount of information in the 'referer' header for cross-origin requests.`

• **Strict site isolation** - `#enable-site-per-process` - [Enabled]

`Experimental security mode that ensures each renderer process contains pages from at most one site. In this mode, out-of-process iframes will be used whenever an iframe is cross-site.`

• **Top document isolation** - `#enable-top-document-isolation` - [Enabled]

`Highly experimental performance mode where cross-site iframes are kept in a separate process from the top document. In this mode, iframes from different third-party sites will be allowed to share a process.`

• **Block scripts loaded via document.write** - `#disallow-doc-written-script-loads` - [Enabled]

`Disallows fetches for third-party parser-blocking scripts inserted into the main frame via document.write.`

• **Cross process frames for guests** - `#cross-process-guests` - [Enabled]

`Highly experimental where guests such as <webview> are implemented on the out-of-process iframe infrastructure.`

_Note:_

The last one is not completely tested (newly enabled by me). I noticed that it have a small disadvandage - 2 clicks needed to come inside the YouTube playlist.

(There is NO bad news relative to your extension this time, probably this is expected behaviour of `<webview>` on the `out-of-process iframe`)

--------------

My question is the next (just for understanding your algo).

**Does your extension takes into account existing Browser (experimental) settings within APIs:**

-- don't touch blocked APIs in the browser, check what kind of APIs may be additionally blocked?

or

-- ignore all browser flags relative to APIs management, overwrite all management with extention settings (turn on/off)?

**Comment by snyderp** [comment]
Howdy, just to answer our last two questions:

> Does your extension takes into account existing Browser (experimental) settings within APIs:

Nope.  The extension only modifies methods in standards documents, with some vendor prefixes I added manually where I knew of them.

> ignore all browser flags relative to APIs management, overwrite all management with extention settings

Nope, the extension will have no affect on the browser flags / configuration management / etc
