### ISSUE TITLE
Edit matching pattern for existing rules

### ISSUE THREAD

**Issue by iWARR** [snyderp/web-api-manager#76]
If I want change/optimize syntax of the existing rule:

1) I have to make a new (refined) custom rule for the same domain name, then repeat all settings manually, then delete the old one.

2) If I'll delete the old one first, I will lose my config forever (and must make a tests of the site again).

These are unacceptable and cause a huge time losses.

-------------

Please, make an option to change the existing rules. Thanks.

**Comment by snyderp** [comment]
@iWARR I think the template system that is in place might be exactly what  you're referring to / looking for.  If not though, please let me know (and describe in more detail if possible) what  you're looking to do, and I'll see whats possible.

Thanks!

**Comment by iWARR** [comment]
I want have an option to **Edit** my rules from the Permitting & Blocking lists, that has been created before.

_For example:_

I have the rule: `*.google.com`
I want quickly edit this to: `*.google.*`

Suggested variants of implementation:

• Make the Pattern "address bar" active to change a names right here + [Apply] button / Enter
• Button [Edit] in the headers of Permitting & Blocking lists
• Your variant

**Comment by snyderp** [comment]
Ah, i understand now what you're asking for here.  I think it'd be nice to add, but I wont get to it for a while.  In the meantime, i suggest the following steps, which should get you most of the way there:

Using your `*.google.com` example:

1. Select `*.google.com` and click save template
2. Create a new `*.google.*` rule and click "apply template"
3. Delete original `*.google.com` rule

Hope that helps!

**Comment by snyderp** [comment]
FYI, I'm working on this now in the `76-edit-rule-match-patterns` branch

**Comment by snyderp** [comment]
fixed in c430ae9
