### ISSUE TITLE
[bug] feature counter reset to 0 after saving template in custom configurations

### ISSUE THREAD

**Issue by n8v8R** [snyderp/web-api-manager#77]
WIN10 _x64 1709 16299.125 with FF58/59/60 _x64
WAM 0.9.25

Save template with at least one Custom blocked feature. Refresh the setting page (F5) and the counter gets reset to 0 every time, however the blocked features remain present in the settings.

Does the bug only impact the counter or does it eventually invalidate the blocked features, albeit still present.

**Comment by snyderp** [comment]
@n8v8R I'm starting in on this now, but for the short term, this (appears, still double checking) to just be a cosmetic bug.  It won't affect whats actually being blocked
