### ISSUE TITLE
standards.js word

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [snyderp/web-api-manager#9]
`...\content_scripts\dist\standards.js`  .. `idenitifer` .. is that meant to be "identifier" (and calls to it elsewhere?). I know its not a typo, because it's used 74 times

```js
      "info": {
         "name": "XMLHttpRequest",
         "subsection_number": null,
         "subsection_name": null,
         "url": "https://xhr.spec.whatwg.org/",
         "idenitifer": "XMLHttpRequest"
      },
```

**Comment by snyderp** [comment]
Ah,  that sure is a typo, from me fat fingering something in the gulp script.  Fixed!  Thanks for the heads up!
