### ISSUE TITLE
WebApiManager still maintained?

### ISSUE THREAD

**Issue by curiosity-seeker** [snyderp/web-api-manager#98]
I'm a bit worried that the development of this excellent add-on seems to be stalled. The latest commit is from Feb. 14, and even more concerning is that the latest comment from @snyderp dates back quite a number of weeks.

So does anybody know what's going on? Is the development of this add-on dead? It would be a pity, indeed.

**Comment by snyderp** [comment]
Apologies, but yes, at the moment I don't have the bandwidth to maintain the project any further.  I would be happy to hand it over to someone else, or co maintain it.  

I've taken a position as a privacy researcher at Brave, where I'm doing similar work on the brave browser, but at the moment am not able to do both unfortunately

**Comment by crssi** [comment]
Nice to hear. I wish you all best.

**Comment by curiosity-seeker** [comment]
@snyderp : Thanks, Peter, for your reply! Congratulations on your job at Brave!

I understand that you're no longer able to maintain the project. But perhaps you could add an info here and on AMO that you're looking for someone to take it over. It would be a tragedy if this valuable add-on would fall into decline.

**Comment by snyderp** [comment]
@curiosity-seeker thanks for the suggestion.  I've added a brief note in both suggestions mentioning that the project is not being maintained.  Hopefully someone will be interested!  I'm happy to co-maintain, but just dont have the time to do it on my own at the moment
